export const MONITORING_PAIRING_CODE_TTL_MINUTES = 30
export const MONITORING_HEARTBEAT_INTERVAL_SECONDS = 5 * 60
export const MONITORING_ACTIVE_WINDOW_MINUTES = 10
export const MONITORING_DEFAULT_DEVICE_NAME = "Zařízení 1"
